# Generated by Django 2.2.12 on 2020-12-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteqna', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
