# Generated by Django 2.2.12 on 2020-12-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteqna', '0005_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
