# Generated by Django 2.2.12 on 2020-12-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websiteqna', '0006_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='pertanyaan',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=100)),
                ('question_detail', models.TextField(max_length=50000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.TextField()),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
    ]
