# Generated by Django 2.2.12 on 2020-12-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteqna', '0007_pertanyaan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pertanyaan',
        ),
    ]
