# Generated by Django 2.2.12 on 2020-12-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteqna', '0009_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
