# Generated by Django 2.2.12 on 2020-12-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteqna', '0011_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='posted_by',
        ),
    ]
