# Generated by Django 2.2.12 on 2020-12-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteqna', '0013_question_posted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
