# Generated by Django 2.2.12 on 2020-12-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteqna', '0016_auto_20201214_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lol',
        ),
    ]
